import type { Metadata } from "next";
import { ThemeProvider } from "@/contexts/ThemeContext";
import App from "./App";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <App>{children}</App>
    </ThemeProvider>
  );
}
